language: node_js
node_js:
- '6'
script: npm run ci
env:
  global:
  - secure: "CZC+BFW0XVAWIQktwxQcx0Ovrbak6yogkAMpndu0AH8cnDiPqdSzouU3Bwxr5FxgSF4gBGzrVA6xRqafeqqMWCC+wEvnYhluebF/OKCa4OHYxTQvKqb7FdVNmeptDzwY1uKqwsO01Zw2UxP08BtYmEB8XGG9/wtuw/H+lV4ErZI="
  - secure: "IWchdDS1e/BgFFtevdxo0CH52IyrD6Xkn1xyUvhG/YE7tII5u+/uGOeCnQOmIsio18Ygu2jle8TXoQugec0Vi/rao93tBATMiwBA74ejOR6otiyLFOiDBm0T0/5LcQMnqH8PPyIGR2hsC2aTfUi70Sb8mGeDp54JdD23SV8rtTM="

