name: simple-slider
ui: jasmine2
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: ie
    version: 10..11
  - name: microsoftedge
    version: latest
scripts:
  - "dist/simpleslider.min.js"

